// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uinupjhrnewjpvzgluku.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVpbnVwamhybmV3anB2emdsdWt1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyMTgxNzAsImV4cCI6MjA2Nzc5NDE3MH0.EKuBBm4V5A5boJLtQ4jt32QdPn6fmIxSHu-32-JKaLA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});